abacus:
  web:
    upload-path : Z:/sunzh/abacus/yingluo/view/web/src/views

spring:
  application:
    name: zzxy
  profiles:
    active: dev
  resources:
    chain:
       cache: false
    static-locations : classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,file:${abacus.web.upload-path}/,file:${abacus.web.upload-path}/static
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/slife?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: xiaoyuaa
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

  aop:
    proxy-target-class: true
  freemarker:
    allow-request-override : false
    allow-session-override : false
    cache : false
    charset : UTF-8
    check-template-location : true
    content-type : text/html
    enabled : true
    expose-request-attributes : false
    expose-session-attributes : false
    expose-spring-macro-helpers : true
    prefer-file-system-access : true
    request-context-attribute: req  #req访问request
    suffix : .ftl
    template-loader-path : classpath:/templates/
    order : 1
    settings :
      template_update_delay : 0
      default_encoding : UTF-8
      classic_compatible : true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xinwei.entity
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.xinwei.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    auto-set-db-type: true
    #驼峰下划线转换
    db-column-underline: true
    refresh-mapper: true
    #metaObjectHandler: com.slife.config.plus.SysMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

shiro:
  realm-class: com.xinwei.config.shiro.MyShiroRealm
  custom-authc-filter-class: com.xinwei.config.shiro.AjaxAuthorizationFilter
  login-url: /login
  success-url: /web/index
  retry-max: 5
  retry-expire-time-redis: 5
  authorization-expire-time-redis: 10
  hash-iterations: 1024
  hash-algorithm-name: SHA-1
  stored-credentials-hex-encoded: false
  session:
      global-session-timeout: 360000
      validation-interval: 1000
      validation-scheduler-enabled: true
  filter-chain-definitions: { "web-xx" : authc}



server:
  port: 8080


attach_path: E:/ideaword/moban/slife/attach/